<?php

  // set the current page; options: TRAINS, ORG, PI PLANNING, TRAINING, REPORTS, ADMIN, LOGIN, HELP, SEARCH
  $nav_selected = "HOME";

  // make the left menu buttons visible; options: YES, NO
  $left_buttons = "NO";

  // set the left menu button selected; options will change based on the main selection
  $left_selected = "";

  include("./nav.php");
?>

<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="images/Full_SAFe_image.png" usemap="#image-map">

<map name="image-map">
   
    <area target="_blank"
          alt="Core Values"
          title="Core Values"
          href="https://www.scaledagileframework.com/safe-core-values/"
          coords="377,780,454,817"
          shape="rect">

</map>

<?php include("./footer.php"); ?>
